---

- name: check mandatory variables
  assert:
    that:
      - kubernetes_version is defined

- name: check ansible_os_family
  assert:
    that: ansible_os_family == "RedHat"
    fail_msg: 'ansible_os_family is "{{ ansible_os_family }}" expected "RedHat"'

- name: get packets facts
  package_facts:
    manager: "rpm"
