---

- hosts: cluster
  gather_facts: yes
  become: yes
  roles:
    - role: check-os
      any_errors_fatal: true

- hosts: cluster
  gather_facts: yes
  become: yes
  roles:
    - role: docker
      tags: docker

- hosts: cluster
  gather_facts: no
  become: yes
  roles:
    - role: nginx_http_health_check
      tags: nginx_http_health_check
      when: nginx_http_health_check

- hosts: cluster
  gather_facts: yes
  become: yes
  roles:
    - role: kubernetes
      tags: kubernetes
