---

- name: check mandatory variables
  assert:
    that:
      - docker_version is defined
      - containerd_version is defined

- name: install yum-utils
  yum:
    name: yum-utils
  
- name: add Docker CE stable repository
  yum_repository:
    name: docker-ce-stable
    file: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: install docker-ce
  yum:
    name:
    - docker-ce-{{ docker_version }}
    - docker-ce-cli-{{ docker_version }}
    - containerd.io-{{ containerd_version }}
    state: present
    allow_downgrade: yes
  notify: docker service restart

- name: ensures /etc/systemd/system/docker.service.d dir exists
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: docker systemd set proxy
  blockinfile:
    path: /etc/systemd/system/docker.service.d/override.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK proxy"
    block: |
      [Service]
      {% if proxy_env.http_proxy is defined %}
      Environment="HTTP_PROXY={{ proxy_env.http_proxy }}"
      {% endif %}
      {% if proxy_env.https_proxy is defined %}
      Environment="HTTPS_PROXY={{ proxy_env.https_proxy }}"
      {% endif %}
      {% if proxy_env.no_proxy is defined %}
      Environment="NO_PROXY={{ proxy_env.no_proxy }}"
      {% endif %}
    create: yes
    state: |-
      {% if 
        proxy_env.http_proxy is defined or
        proxy_env.https_proxy is defined or
        proxy_env.no_proxy is defined
      %}
      present
      {%- else %}
      absent
      {%- endif %}
  notify: docker service restart

- name: ensures /etc/docker dir exists
  file:
    path: /etc/docker
    state: directory

- name: copy docker daemon.json config
  copy:
    content: "{{ docker_conf | default('') }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: docker service restart
